<?php
namespace OpenSubtitles;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-16 at 18:37:53.
 */
class SubtitlesManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SubtitlesManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SubtitlesManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OpenSubtitles\SubtitlesManager::getSubtitles
     * @todo   Implement testGetSubtitles().
     */
    public function testGetSubtitles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
